apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - name: 80-vproapp-port
    port: 80
    protocol: TCP
    targetPort: vproapp-port
  selector:
    app: vproapp
  type: LoadBalancer