apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
  - name: 3306-vprodb-port
    port: 3306
    protocol: TCP
    targetPort: vprodb-port
  selector:
    app: vprodb
  type: ClusterIP
