apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
  - name: 11211-vpromc-port
    port: 11211
    protocol: TCP
    targetPort: vpromc-port
  selector:
    app: vpromc
  type: ClusterIP
