apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vpromq01
  name: vpromq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromq01
  template:
    metadata:
      labels:
        app: vpromq01
    spec:
      containers:
      - image: rabbitmq
        name: vpromq01
        ports:
        - containerPort: 15672
          name: vpromq01-port
        env:
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: rmq-pass
          - name: RABBITMQ_DEFAULT_USER
            value: guest

