apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
  - name: 15672-vpromq01-port
    port: 15672
    protocol: TCP
    targetPort: vpromq01-port
  selector:
    app: vpromq01
  type: ClusterIP
